package message

// Role represents the role of a message sender in a conversation.
// It follows the standard LLM API conventions for message roles.
type Role string

const (
	// RoleSystem represents system-level instructions that guide model behavior.
	RoleSystem Role = "system"

	// RoleUser represents messages from the end user.
	RoleUser Role = "user"

	// RoleAssistant represents messages generated by the AI model.
	RoleAssistant Role = "assistant"

	// RoleTool represents messages containing tool execution results.
	RoleTool Role = "tool"

	// RoleFunction represents messages containing function call results.
	// Deprecated: Use RoleTool instead for most providers.
	RoleFunction Role = "function"
)

// IsValid returns true if the Role is one of the recognized role constants.
func (r Role) IsValid() bool {
	switch r {
	case RoleSystem, RoleUser, RoleAssistant, RoleTool, RoleFunction:
		return true
	default:
		return false
	}
}

// String returns the string representation of the Role.
func (r Role) String() string {
	return string(r)
}
