// Package orchestra provides the public API for the Orchestra multi-agent
// AI orchestration engine.
//
// Orchestra is a Go-based framework for orchestrating multiple AI agents that
// use different LLM providers (OpenAI, Anthropic, Google Gemini, Ollama, etc.)
// and models. It provides a unified abstraction layer over heterogeneous LLM
// backends and enables complex multi-agent workflows.
//
// # Quick Start
//
// Register a provider and generate a completion:
//
//	p, err := orchestra.NewMockProvider("test")
//	if err != nil {
//	    log.Fatal(err)
//	}
//	result, err := p.Generate(ctx, orchestra.GenerateRequest{
//	    Model:    "mock-model",
//	    Messages: []orchestra.Message{orchestra.UserMessage("Hello!")},
//	})
//
// # Functional Options
//
// Use functional options to configure generation parameters:
//
//	opts := orchestra.NewGenerateOptions(
//	    orchestra.WithTemperature(0.7),
//	    orchestra.WithMaxTokens(1024),
//	    orchestra.WithJSONMode(),
//	)
//
// # Configuration
//
// Load configuration from YAML or environment variables:
//
//	cfg, err := orchestra.LoadConfig("configs/orchestra.yaml")
//	cfg := orchestra.LoadConfigFromEnv()
//
// # Provider Registry
//
// Use the global registry to manage providers:
//
//	orchestra.RegisterProvider("openai", factory, orchestra.ProviderConfig{...})
//	orchestra.AliasProvider("gpt4", "openai::gpt-4-turbo")
//	p, model, err := orchestra.ResolveModel("gpt4")
package orchestra

import (
	"log/slog"
	"time"

	"github.com/user/orchestra/internal/config"
	"github.com/user/orchestra/internal/message"
	"github.com/user/orchestra/internal/middleware"
	"github.com/user/orchestra/internal/provider"
	"github.com/user/orchestra/internal/provider/anthropic"
	"github.com/user/orchestra/internal/provider/cohere"
	"github.com/user/orchestra/internal/provider/gemini"
	"github.com/user/orchestra/internal/provider/mistral"
	"github.com/user/orchestra/internal/provider/mock"
	"github.com/user/orchestra/internal/provider/ollama"
	"github.com/user/orchestra/internal/provider/openai"
)

// ---------------------------------------------------------------------------
// Message Types
// ---------------------------------------------------------------------------

// Role represents the role of a message sender in a conversation.
type Role = message.Role

const (
	// RoleSystem represents system-level instructions that guide model behavior.
	RoleSystem = message.RoleSystem

	// RoleUser represents messages from the end user.
	RoleUser = message.RoleUser

	// RoleAssistant represents messages generated by the AI model.
	RoleAssistant = message.RoleAssistant

	// RoleTool represents messages containing tool execution results.
	RoleTool = message.RoleTool

	// RoleFunction represents messages containing function call results.
	RoleFunction = message.RoleFunction
)

// Message represents a single message within a conversation.
type Message = message.Message

// ContentBlock represents a single piece of content within a message.
type ContentBlock = message.ContentBlock

// ToolCall represents a single tool/function call requested by the model.
type ToolCall = message.ToolCall

// ToolCallFunction represents the function details within a tool call.
type ToolCallFunction = message.ToolCallFunction

// ToolResult holds the result of executing a tool call.
type ToolResult = message.ToolResult

// Conversation represents an ordered sequence of messages exchanged
// within a single interaction session with an LLM provider.
type Conversation = message.Conversation

// Message constructors

// TextMessage creates a new Message with a single text content block.
func TextMessage(role Role, text string) Message {
	return message.TextMessage(role, text)
}

// SystemMessage creates a new system message with the given text.
func SystemMessage(text string) Message {
	return message.SystemMessage(text)
}

// UserMessage creates a new user message with the given text.
func UserMessage(text string) Message {
	return message.UserMessage(text)
}

// AssistantMessage creates a new assistant message with the given text.
func AssistantMessage(text string) Message {
	return message.AssistantMessage(text)
}

// ToolResultMessage creates a new tool result message.
func ToolResultMessage(toolCallID, content string, isError bool) Message {
	return message.ToolResultMessage(toolCallID, content, isError)
}

// AssistantToolCallMessage creates a new assistant message containing tool calls.
func AssistantToolCallMessage(toolCalls []ToolCall) Message {
	return message.AssistantToolCallMessage(toolCalls)
}

// Content block constructors

// TextContentBlock creates a new ContentBlock of type "text" with the given string.
func TextContentBlock(text string) ContentBlock {
	return message.TextContentBlock(text)
}

// ImageContentBlock creates a new ContentBlock of type "image" with the given URL.
func ImageContentBlock(imageURL, mimeType string) ContentBlock {
	return message.ImageContentBlock(imageURL, mimeType)
}

// FileContentBlock creates a new ContentBlock of type "file" with the given data.
func FileContentBlock(data []byte, mimeType string) ContentBlock {
	return message.FileContentBlock(data, mimeType)
}

// Conversation constructors

// NewConversation creates a new Conversation with a randomly generated ID.
func NewConversation() *Conversation {
	return message.NewConversation()
}

// NewConversationWithID creates a new Conversation with the specified ID.
func NewConversationWithID(id string) *Conversation {
	return message.NewConversationWithID(id)
}

// ---------------------------------------------------------------------------
// Provider Types
// ---------------------------------------------------------------------------

// Provider is the core interface that all LLM backends must implement.
type Provider = provider.Provider

// GenerateRequest represents a request to generate a completion from a model.
type GenerateRequest = provider.GenerateRequest

// GenerateResult holds the result of a single completion generation.
type GenerateResult = provider.GenerateResult

// GenerateOptions configures how a model generates its response.
type GenerateOptions = provider.GenerateOptions

// GenerateOption is a functional option for configuring GenerateOptions.
type GenerateOption = provider.GenerateOption

// StreamEvent represents a single event in a streaming response.
type StreamEvent = provider.StreamEvent

// StreamEventType identifies the kind of event in a response stream.
type StreamEventType = provider.StreamEventType

const (
	// StreamEventStart is emitted once when streaming begins.
	StreamEventStart = provider.StreamEventStart

	// StreamEventChunk is emitted for each token or text fragment.
	StreamEventChunk = provider.StreamEventChunk

	// StreamEventToolCall is emitted when the model requests a tool call.
	StreamEventToolCall = provider.StreamEventToolCall

	// StreamEventDone is emitted once when streaming completes successfully.
	StreamEventDone = provider.StreamEventDone

	// StreamEventError is emitted when an error occurs during streaming.
	StreamEventError = provider.StreamEventError
)

// FinishReason indicates why the model stopped generating tokens.
type FinishReason = provider.FinishReason

const (
	// FinishReasonStop indicates the model generated a natural stop point.
	FinishReasonStop = provider.FinishReasonStop

	// FinishReasonLength indicates generation stopped due to max tokens.
	FinishReasonLength = provider.FinishReasonLength

	// FinishReasonToolCall indicates the model requested tool execution.
	FinishReasonToolCall = provider.FinishReasonToolCall

	// FinishReasonContentFilter indicates generation was stopped by content filter.
	FinishReasonContentFilter = provider.FinishReasonContentFilter

	// FinishReasonError indicates generation stopped due to an error.
	FinishReasonError = provider.FinishReasonError
)

// TokenUsage tracks token consumption for a single request.
type TokenUsage = provider.TokenUsage

// ModelCapabilities describes the features a specific model supports.
type ModelCapabilities = provider.ModelCapabilities

// ModelInfo describes a model available from a provider.
type ModelInfo = provider.ModelInfo

// ResponseFormat specifies how the model should format its output.
type ResponseFormat = provider.ResponseFormat

// ToolDefinition defines a tool that the model can invoke.
type ToolDefinition = provider.ToolDefinition

// FunctionDef describes a function that can be called by the model.
type FunctionDef = provider.FunctionDef

// ProviderError wraps an error from a provider with additional context.
type ProviderError = provider.ProviderError

// ProviderFactory is a function that creates a new Provider instance.
type ProviderFactory = provider.ProviderFactory

// ---------------------------------------------------------------------------
// Functional Options
// ---------------------------------------------------------------------------

// NewGenerateOptions creates a GenerateOptions by applying the given
// functional options to a zero-valued GenerateOptions.
func NewGenerateOptions(opts ...GenerateOption) GenerateOptions {
	return provider.NewGenerateOptions(opts...)
}

// WithTemperature sets the generation temperature.
func WithTemperature(t float64) GenerateOption {
	return provider.WithTemperature(t)
}

// WithTopP sets the top-p sampling parameter.
func WithTopP(p float64) GenerateOption {
	return provider.WithTopP(p)
}

// WithMaxTokens sets the maximum number of output tokens.
func WithMaxTokens(n int) GenerateOption {
	return provider.WithMaxTokens(n)
}

// WithStopSequences sets the stop sequences that halt generation.
func WithStopSequences(seqs ...string) GenerateOption {
	return provider.WithStopSequences(seqs...)
}

// WithSeed sets the deterministic sampling seed.
func WithSeed(s int64) GenerateOption {
	return provider.WithSeed(s)
}

// WithResponseFormat sets the output format constraint.
func WithResponseFormat(rf *ResponseFormat) GenerateOption {
	return provider.WithResponseFormat(rf)
}

// WithJSONMode enables JSON object output mode.
func WithJSONMode() GenerateOption {
	return provider.WithJSONMode()
}

// WithTextMode enables plain text output mode.
func WithTextMode() GenerateOption {
	return provider.WithTextMode()
}

// WithJSONSchema enables structured JSON output conforming to the schema.
func WithJSONSchema(schema map[string]any) GenerateOption {
	return provider.WithJSONSchema(schema)
}

// WithExtra sets a provider-specific option.
func WithExtra(key string, value any) GenerateOption {
	return provider.WithExtra(key, value)
}

// Response format constructors

// TextResponseFormat creates a ResponseFormat for plain text output.
func TextResponseFormat() *ResponseFormat {
	return provider.TextResponseFormat()
}

// JSONResponseFormat creates a ResponseFormat for JSON object output.
func JSONResponseFormat() *ResponseFormat {
	return provider.JSONResponseFormat()
}

// JSONSchemaResponseFormat creates a ResponseFormat for structured JSON output.
func JSONSchemaResponseFormat(schema map[string]any) *ResponseFormat {
	return provider.JSONSchemaResponseFormat(schema)
}

// Tool constructors

// FunctionTool creates a ToolDefinition for a function-type tool.
func FunctionTool(name, description string, parameters map[string]any) ToolDefinition {
	return provider.FunctionTool(name, description, parameters)
}

// Error constructors

// NewProviderError creates a new ProviderError.
func NewProviderError(providerName, model string, err error) *ProviderError {
	return provider.NewProviderError(providerName, model, err)
}

// NewProviderErrorWithCode creates a new ProviderError with a code and HTTP status.
func NewProviderErrorWithCode(providerName, model, code string, statusCode int, err error) *ProviderError {
	return provider.NewProviderErrorWithCode(providerName, model, code, statusCode, err)
}

// ---------------------------------------------------------------------------
// Provider Registry
// ---------------------------------------------------------------------------

// Registry manages the creation and lookup of Provider instances.
type Registry = provider.Registry

// NewRegistry creates a new empty provider registry.
func NewRegistry() *Registry {
	return provider.NewRegistry()
}

// Global registry functions

// RegisterProvider registers a provider factory in the global registry.
func RegisterProvider(name string, factory ProviderFactory, cfg config.ProviderConfig) error {
	return provider.Register(name, factory, cfg)
}

// MustRegisterProvider registers a provider factory, panicking on error.
func MustRegisterProvider(name string, factory ProviderFactory, cfg config.ProviderConfig) {
	provider.MustRegister(name, factory, cfg)
}

// GetProvider retrieves a provider from the global registry.
func GetProvider(name string) (Provider, error) {
	return provider.Get(name)
}

// ResolveModel resolves a model reference using the global registry.
// Accepts "provider::model", alias, or bare model name.
func ResolveModel(modelRef string) (Provider, string, error) {
	return provider.Resolve(modelRef)
}

// AliasProvider registers an alias in the global registry.
func AliasProvider(shortName, modelRef string) error {
	return provider.Alias(shortName, modelRef)
}

// MustAliasProvider registers an alias, panicking on error.
func MustAliasProvider(shortName, modelRef string) {
	provider.MustAlias(shortName, modelRef)
}

// GlobalRegistry is the default global provider registry.
var GlobalRegistry = provider.GlobalRegistry

// ---------------------------------------------------------------------------
// Mock Provider (for testing)
// ---------------------------------------------------------------------------

// MockProvider is a mock implementation of the Provider interface for testing.
type MockProvider = mock.Provider

// MockResponse configures what the mock provider returns for a Generate call.
type MockResponse = mock.MockResponse

// StreamChunk configures a single chunk in a streaming response.
type StreamChunk = mock.StreamChunk

// MockModelConfig describes a model available in the mock provider.
// Named MockModelConfig to avoid collision with config.ModelConfig.
type MockModelConfig = mock.ModelConfig

// NewMockProvider creates a new mock provider with the given name.
func NewMockProvider(name string) *MockProvider {
	return mock.NewProvider(name)
}

// ---------------------------------------------------------------------------
// Provider Factories (Phase 2)
// ---------------------------------------------------------------------------
//
// Each provider factory creates a new provider.Provider from a ProviderConfig.
// Register them with the global registry:
//
//	orchestra.RegisterProvider("openai", orchestra.OpenAIFactory, cfg)
//	orchestra.RegisterProvider("anthropic", orchestra.AnthropicFactory, cfg)

// OpenAIFactory creates a new OpenAI provider from the given configuration.
// Requires cfg.APIKey to be set. Supports GPT-4o, GPT-4-Turbo, o1/o3, etc.
var OpenAIFactory = openai.Factory

// AnthropicFactory creates a new Anthropic provider from the given configuration.
// Requires cfg.APIKey to be set. Supports Claude Sonnet, Opus, Haiku models.
var AnthropicFactory = anthropic.Factory

// GeminiFactory creates a new Google Gemini provider from the given configuration.
// Requires cfg.APIKey to be set. Supports Gemini 2.5/2.0/1.5 models.
var GeminiFactory = gemini.Factory

// OllamaFactory creates a new Ollama provider from the given configuration.
// Does not require an API key. Uses cfg.BaseURL (defaults to http://localhost:11434).
var OllamaFactory = ollama.Factory

// MistralFactory creates a new Mistral AI provider from the given configuration.
// Requires cfg.APIKey to be set. Supports Mistral Large, Medium, Small, Nemo.
var MistralFactory = mistral.Factory

// CohereFactory creates a new Cohere provider from the given configuration.
// Requires cfg.APIKey to be set. Supports Command R+, Command R, Aya models.
var CohereFactory = cohere.Factory

// NewOpenAIProvider creates a new OpenAI provider directly.
func NewOpenAIProvider(cfg ProviderConfig) (*openai.Provider, error) {
	return openai.NewProvider(cfg)
}

// NewAnthropicProvider creates a new Anthropic provider directly.
func NewAnthropicProvider(cfg ProviderConfig) (*anthropic.Provider, error) {
	return anthropic.NewProvider(cfg)
}

// NewGeminiProvider creates a new Google Gemini provider directly.
func NewGeminiProvider(cfg ProviderConfig) (*gemini.Provider, error) {
	return gemini.NewProvider(cfg)
}

// NewOllamaProvider creates a new Ollama provider directly.
func NewOllamaProvider(cfg ProviderConfig) (*ollama.Provider, error) {
	return ollama.NewProvider(cfg)
}

// NewMistralProvider creates a new Mistral provider directly.
func NewMistralProvider(cfg ProviderConfig) (*mistral.Provider, error) {
	return mistral.NewProvider(cfg)
}

// NewCohereProvider creates a new Cohere provider directly.
func NewCohereProvider(cfg ProviderConfig) (*cohere.Provider, error) {
	return cohere.NewProvider(cfg)
}

// RegisterAllProviders registers all built-in provider factories into the
// given registry using the provided configuration map. Only providers with
// a corresponding entry in the configs map will be registered.
//
// Example:
//
//	cfg, _ := orchestra.LoadConfig("orchestra.yaml")
//	registry := orchestra.NewRegistry()
//	orchestra.RegisterAllProviders(registry, cfg.Providers)
func RegisterAllProviders(reg *Registry, configs map[string]ProviderConfig) {
	factories := map[string]ProviderFactory{
		"openai":    OpenAIFactory,
		"anthropic": AnthropicFactory,
		"gemini":    GeminiFactory,
		"ollama":    OllamaFactory,
		"mistral":   MistralFactory,
		"cohere":    CohereFactory,
	}
	for name, factory := range factories {
		if cfg, ok := configs[name]; ok {
			if cfg.IsEnabled() {
				reg.MustRegister(name, factory, cfg)
			}
		}
	}
}

// ---------------------------------------------------------------------------
// Middleware (Phase 2)
// ---------------------------------------------------------------------------
//
// Middleware wraps providers with cross-cutting concerns like retry,
// rate limiting, logging, caching, and circuit breaking.
//
// Compose multiple middleware using Chain:
//
//	p := orchestra.Chain(
//	    orchestra.WithLogging(slog.Default()),
//	    orchestra.WithCircuitBreaker(5, 30*time.Second),
//	    orchestra.WithRetry(3, nil),
//	    orchestra.WithRateLimit(60, 0),
//	)(baseProvider)

// ProviderMiddleware is a function that wraps a Provider with additional behavior.
type ProviderMiddleware = middleware.ProviderMiddleware

// BackoffStrategy calculates the delay between retry attempts.
type BackoffStrategy = middleware.BackoffStrategy

// ExponentialBackoff implements BackoffStrategy with exponential delays and jitter.
type ExponentialBackoff = middleware.ExponentialBackoff

// ConstantBackoff implements BackoffStrategy with a fixed delay.
type ConstantBackoff = middleware.ConstantBackoff

// CacheStore is the interface for caching Generate results.
type CacheStore = middleware.CacheStore

// MemoryCacheStore implements CacheStore with an in-memory map.
type MemoryCacheStore = middleware.MemoryCacheStore

// CircuitState represents the state of a circuit breaker.
type CircuitState = middleware.CircuitState

// CircuitBreakerStats holds current circuit breaker statistics.
type CircuitBreakerStats = middleware.CircuitBreakerStats

const (
	// CircuitClosed means requests flow through normally.
	CircuitClosed = middleware.CircuitClosed
	// CircuitOpen means requests are rejected immediately.
	CircuitOpen = middleware.CircuitOpen
	// CircuitHalfOpen means a limited number of requests probe for recovery.
	CircuitHalfOpen = middleware.CircuitHalfOpen
)

// WithRetry returns a middleware that retries failed requests up to maxAttempts
// times with the given backoff strategy. Pass nil for backoff to use defaults
// (exponential with jitter, starting at 1s, max 30s).
func WithRetry(maxAttempts int, backoff BackoffStrategy) ProviderMiddleware {
	return middleware.WithRetry(maxAttempts, backoff)
}

// WithRateLimit returns a middleware that limits the rate of requests.
// rpm is requests per minute; tpm is tokens per minute. Zero means unlimited.
func WithRateLimit(rpm, tpm int) ProviderMiddleware {
	return middleware.WithRateLimit(rpm, tpm)
}

// WithLogging returns a middleware that logs each request with structured logging.
// Pass nil for logger to use slog.Default().
func WithLogging(logger *slog.Logger) ProviderMiddleware {
	return middleware.WithLogging(logger)
}

// WithCaching returns a middleware that caches Generate results.
// Stream calls are never cached. Tool call results are not cached.
func WithCaching(store CacheStore, ttl time.Duration) ProviderMiddleware {
	return middleware.WithCaching(store, ttl)
}

// WithCircuitBreaker returns a middleware implementing the circuit breaker pattern.
// After threshold consecutive failures, the circuit opens for resetTimeout duration.
func WithCircuitBreaker(threshold int, resetTimeout time.Duration) ProviderMiddleware {
	return middleware.WithCircuitBreaker(threshold, resetTimeout)
}

// Chain composes multiple middleware into a single ProviderMiddleware.
// The first middleware in the list is the outermost wrapper.
func Chain(middlewares ...ProviderMiddleware) ProviderMiddleware {
	return middleware.Chain(middlewares...)
}

// NewMemoryCacheStore creates a new in-memory cache store.
func NewMemoryCacheStore() *MemoryCacheStore {
	return middleware.NewMemoryCacheStore()
}

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

// Config is the top-level configuration for the Orchestra framework.
type Config = config.Config

// ProviderConfig holds the configuration for a single LLM provider.
// This is the canonical type used by both the config loader and the
// provider registry — there is no separate provider-specific config type.
type ProviderConfig = config.ProviderConfig

// LoggingConfig configures the logging subsystem.
type LoggingConfig = config.LoggingConfig

// ObservabilityConfig configures tracing and metrics collection.
type ObservabilityConfig = config.ObservabilityConfig

// TracingConfig configures distributed tracing.
type TracingConfig = config.TracingConfig

// MetricsConfig configures metrics collection and export.
type MetricsConfig = config.MetricsConfig

// AgentDefaults holds default configuration values applied to all agents.
type AgentDefaults = config.AgentDefaults

// ModelConfig holds model-specific configuration overrides from the config package.
// This is distinct from MockModelConfig (the mock provider's model type).
type ModelConfig = config.ModelConfig

// RateLimitConfig configures rate limiting behavior for a provider.
type RateLimitConfig = config.RateLimitConfig

// RetryConfig configures retry behavior for transient failures.
type RetryConfig = config.RetryConfig

// LoadConfig reads configuration from a YAML file with environment variable
// interpolation. Returns an error if the file cannot be read, parsed, or
// if validation fails.
func LoadConfig(path string) (*Config, error) {
	return config.LoadFromFile(path)
}

// LoadConfigFromEnv loads configuration exclusively from environment variables
// prefixed with ORCHESTRA_.
func LoadConfigFromEnv() *Config {
	return config.LoadFromEnv()
}

// LoadConfigOrDefault attempts to load configuration from the given file path.
// If the file does not exist, it returns the default configuration.
func LoadConfigOrDefault(path string) (*Config, error) {
	return config.LoadOrDefault(path)
}

// DefaultConfig returns a Config with sensible defaults.
func DefaultConfig() *Config {
	return config.DefaultConfig()
}

// MergeConfig merges multiple Configs together. Later configs override earlier ones.
func MergeConfig(configs ...*Config) *Config {
	return config.Merge(configs...)
}
