// Package orchestra provides the public API for the Orchestra multi-agent
// AI orchestration engine.
//
// Orchestra is a Go-based framework for orchestrating multiple AI agents that
// use different LLM providers (OpenAI, Anthropic, Google Gemini, Ollama, etc.)
// and models. It provides a unified abstraction layer over heterogeneous LLM
// backends and enables complex multi-agent workflows.
//
// # Quick Start
//
// Register a provider and generate a completion:
//
//	p, err := orchestra.NewMockProvider("test")
//	if err != nil {
//	    log.Fatal(err)
//	}
//	result, err := p.Generate(ctx, orchestra.GenerateRequest{
//	    Model:    "mock-model",
//	    Messages: []orchestra.Message{orchestra.UserMessage("Hello!")},
//	})
//
// # Configuration
//
// Load configuration from YAML or environment variables:
//
//	cfg, err := orchestra.LoadConfig("configs/orchestra.yaml")
//	cfg := orchestra.LoadConfigFromEnv()
//
// # Provider Registry
//
// Use the global registry to manage providers:
//
//	orchestra.RegisterProvider("openai", factory, orchestra.ProviderConfig{...})
//	orchestra.AliasProvider("gpt4", "openai::gpt-4-turbo")
//	p, model, err := orchestra.ResolveModel("gpt4")
package orchestra

import (
	"context"

	"github.com/user/orchestra/internal/config"
	"github.com/user/orchestra/internal/message"
	"github.com/user/orchestra/internal/provider"
	"github.com/user/orchestra/internal/provider/mock"
)

// ---------------------------------------------------------------------------
// Message Types
// ---------------------------------------------------------------------------

// Role represents the role of a message sender in a conversation.
type Role = message.Role

const (
	// RoleSystem represents system-level instructions that guide model behavior.
	RoleSystem = message.RoleSystem

	// RoleUser represents messages from the end user.
	RoleUser = message.RoleUser

	// RoleAssistant represents messages generated by the AI model.
	RoleAssistant = message.RoleAssistant

	// RoleTool represents messages containing tool execution results.
	RoleTool = message.RoleTool

	// RoleFunction represents messages containing function call results.
	RoleFunction = message.RoleFunction
)

// Message represents a single message within a conversation.
type Message = message.Message

// ContentBlock represents a single piece of content within a message.
type ContentBlock = message.ContentBlock

// ToolCall represents a single tool/function call requested by the model.
type ToolCall = message.ToolCall

// ToolCallFunction represents the function details within a tool call.
type ToolCallFunction = message.ToolCallFunction

// ToolResult holds the result of executing a tool call.
type ToolResult = message.ToolResult

// Conversation represents an ordered sequence of messages exchanged
// within a single interaction session with an LLM provider.
type Conversation = message.Conversation

// Message constructors

// TextMessage creates a new Message with a single text content block.
func TextMessage(role Role, text string) Message {
	return message.TextMessage(role, text)
}

// SystemMessage creates a new system message with the given text.
func SystemMessage(text string) Message {
	return message.SystemMessage(text)
}

// UserMessage creates a new user message with the given text.
func UserMessage(text string) Message {
	return message.UserMessage(text)
}

// AssistantMessage creates a new assistant message with the given text.
func AssistantMessage(text string) Message {
	return message.AssistantMessage(text)
}

// ToolResultMessage creates a new tool result message.
func ToolResultMessage(toolCallID, content string, isError bool) Message {
	return message.ToolResultMessage(toolCallID, content, isError)
}

// AssistantToolCallMessage creates a new assistant message containing tool calls.
func AssistantToolCallMessage(toolCalls []ToolCall) Message {
	return message.AssistantToolCallMessage(toolCalls)
}

// Content block constructors

// TextContentBlock creates a new ContentBlock of type "text" with the given string.
func TextContentBlock(text string) ContentBlock {
	return message.TextContentBlock(text)
}

// ImageContentBlock creates a new ContentBlock of type "image" with the given URL.
func ImageContentBlock(imageURL, mimeType string) ContentBlock {
	return message.ImageContentBlock(imageURL, mimeType)
}

// FileContentBlock creates a new ContentBlock of type "file" with the given data.
func FileContentBlock(data []byte, mimeType string) ContentBlock {
	return message.FileContentBlock(data, mimeType)
}

// Conversation constructors

// NewConversation creates a new Conversation with a randomly generated ID.
func NewConversation() *Conversation {
	return message.NewConversation()
}

// NewConversationWithID creates a new Conversation with the specified ID.
func NewConversationWithID(id string) *Conversation {
	return message.NewConversationWithID(id)
}

// ---------------------------------------------------------------------------
// Provider Types
// ---------------------------------------------------------------------------

// Provider is the core interface that all LLM backends must implement.
type Provider = provider.Provider

// GenerateRequest represents a request to generate a completion from a model.
type GenerateRequest = provider.GenerateRequest

// GenerateResult holds the result of a single completion generation.
type GenerateResult = provider.GenerateResult

// GenerateOptions configures how a model generates its response.
type GenerateOptions = provider.GenerateOptions

// StreamEvent represents a single event in a streaming response.
type StreamEvent = provider.StreamEvent

// StreamEventType identifies the kind of event in a response stream.
type StreamEventType = provider.StreamEventType

const (
	// StreamEventStart is emitted once when streaming begins.
	StreamEventStart = provider.StreamEventStart

	// StreamEventChunk is emitted for each token or text fragment.
	StreamEventChunk = provider.StreamEventChunk

	// StreamEventToolCall is emitted when the model requests a tool call.
	StreamEventToolCall = provider.StreamEventToolCall

	// StreamEventDone is emitted once when streaming completes successfully.
	StreamEventDone = provider.StreamEventDone

	// StreamEventError is emitted when an error occurs during streaming.
	StreamEventError = provider.StreamEventError
)

// FinishReason indicates why the model stopped generating tokens.
type FinishReason = provider.FinishReason

const (
	// FinishReasonStop indicates the model generated a natural stop point.
	FinishReasonStop = provider.FinishReasonStop

	// FinishReasonLength indicates generation stopped due to max tokens.
	FinishReasonLength = provider.FinishReasonLength

	// FinishReasonToolCall indicates the model requested tool execution.
	FinishReasonToolCall = provider.FinishReasonToolCall

	// FinishReasonContentFilter indicates generation was stopped by content filter.
	FinishReasonContentFilter = provider.FinishReasonContentFilter

	// FinishReasonError indicates generation stopped due to an error.
	FinishReasonError = provider.FinishReasonError
)

// TokenUsage tracks token consumption for a single request.
type TokenUsage = provider.TokenUsage

// ModelCapabilities describes the features a specific model supports.
type ModelCapabilities = provider.ModelCapabilities

// ModelInfo describes a model available from a provider.
type ModelInfo = provider.ModelInfo

// ResponseFormat specifies how the model should format its output.
type ResponseFormat = provider.ResponseFormat

// ToolDefinition defines a tool that the model can invoke.
type ToolDefinition = provider.ToolDefinition

// FunctionDef describes a function that can be called by the model.
type FunctionDef = provider.FunctionDef

// ProviderConfig holds the configuration needed to create a Provider instance.
type ProviderConfig = provider.ProviderConfig

// RateLimitConfig configures rate limiting behavior for a provider.
type RateLimitConfig = provider.RateLimitConfig

// RetryConfig configures retry behavior for transient failures.
type RetryConfig = provider.RetryConfig

// ProviderFactory is a function that creates a new Provider instance.
type ProviderFactory = provider.ProviderFactory

// ProviderError wraps an error from a provider with additional context.
type ProviderError = provider.ProviderError

// Response format constructors

// TextResponseFormat creates a ResponseFormat for plain text output.
func TextResponseFormat() *ResponseFormat {
	return provider.TextResponseFormat()
}

// JSONResponseFormat creates a ResponseFormat for JSON object output.
func JSONResponseFormat() *ResponseFormat {
	return provider.JSONResponseFormat()
}

// JSONSchemaResponseFormat creates a ResponseFormat for structured JSON output.
func JSONSchemaResponseFormat(schema map[string]any) *ResponseFormat {
	return provider.JSONSchemaResponseFormat(schema)
}

// Tool constructors

// FunctionTool creates a ToolDefinition for a function-type tool.
func FunctionTool(name, description string, parameters map[string]any) ToolDefinition {
	return provider.FunctionTool(name, description, parameters)
}

// Error constructors

// NewProviderError creates a new ProviderError.
func NewProviderError(providerName, model string, err error) *ProviderError {
	return provider.NewProviderError(providerName, model, err)
}

// ---------------------------------------------------------------------------
// Provider Registry
// ---------------------------------------------------------------------------

// Registry manages the creation and lookup of Provider instances.
type Registry = provider.Registry

// NewRegistry creates a new empty provider registry.
func NewRegistry() *Registry {
	return provider.NewRegistry()
}

// Global registry functions

// RegisterProvider registers a provider factory in the global registry.
func RegisterProvider(name string, factory ProviderFactory, config ProviderConfig) error {
	return provider.Register(name, factory, config)
}

// MustRegisterProvider registers a provider factory, panicking on error.
func MustRegisterProvider(name string, factory ProviderFactory, config ProviderConfig) {
	provider.MustRegister(name, factory, config)
}

// GetProvider retrieves a provider from the global registry.
func GetProvider(name string) (Provider, error) {
	return provider.Get(name)
}

// ResolveModel resolves a model reference using the global registry.
// Accepts "provider::model", alias, or bare model name.
func ResolveModel(modelRef string) (Provider, string, error) {
	return provider.Resolve(modelRef)
}

// AliasProvider registers an alias in the global registry.
func AliasProvider(shortName, modelRef string) error {
	return provider.Alias(shortName, modelRef)
}

// MustAliasProvider registers an alias, panicking on error.
func MustAliasProvider(shortName, modelRef string) {
	provider.MustAlias(shortName, modelRef)
}

// GlobalRegistry is the default global provider registry.
var GlobalRegistry = provider.GlobalRegistry

// ---------------------------------------------------------------------------
// Mock Provider (for testing)
// ---------------------------------------------------------------------------

// MockProvider is a mock implementation of the Provider interface for testing.
type MockProvider = mock.Provider

// MockResponse configures what the mock provider returns for a Generate call.
type MockResponse = mock.MockResponse

// StreamChunk configures a single chunk in a streaming response.
type StreamChunk = mock.StreamChunk

// ModelConfig describes a model available in the mock provider.
type ModelConfig = mock.ModelConfig

// NewMockProvider creates a new mock provider with the given name.
func NewMockProvider(name string) *MockProvider {
	return mock.NewProvider(name)
}

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

// Config is the top-level configuration for the Orchestra framework.
type Config = config.Config

// LoggingConfig configures the logging subsystem.
type LoggingConfig = config.LoggingConfig

// ObservabilityConfig configures tracing and metrics collection.
type ObservabilityConfig = config.ObservabilityConfig

// TracingConfig configures distributed tracing.
type TracingConfig = config.TracingConfig

// MetricsConfig configures metrics collection and export.
type MetricsConfig = config.MetricsConfig

// AgentDefaults holds default configuration values applied to all agents.
type AgentDefaults = config.AgentDefaults

// ModelConfig (from config package) holds model-specific configuration overrides.
//
// Note: This is different from mock.ModelConfig. Use the fully qualified
// config package name if you need to disambiguate.
type ConfigModelConfig = config.ModelConfig

// LoadConfig reads configuration from a YAML file with environment variable
// interpolation. Returns an error if the file cannot be read, parsed, or
// if validation fails.
func LoadConfig(path string) (*Config, error) {
	return config.LoadFromFile(path)
}

// LoadConfigFromEnv loads configuration exclusively from environment variables
// prefixed with ORCHESTRA_.
func LoadConfigFromEnv() *Config {
	return config.LoadFromEnv()
}

// LoadConfigOrDefault attempts to load configuration from the given file path.
// If the file does not exist, it returns the default configuration.
func LoadConfigOrDefault(path string) (*Config, error) {
	return config.LoadOrDefault(path)
}

// DefaultConfig returns a Config with sensible defaults.
func DefaultConfig() *Config {
	return config.DefaultConfig()
}

// MergeConfig merges multiple Configs together. Later configs override earlier ones.
func MergeConfig(configs ...*Config) *Config {
	return config.Merge(configs...)
}

// ---------------------------------------------------------------------------
// Context helpers
// ---------------------------------------------------------------------------

// The following type aliases ensure that the public API has access to
// context.Context without requiring additional imports in consumer code.
// This is purely for documentation clarity; consumers still need to import
// "context" in their own code.

// No-op type alias for documentation — consumers use context.Context directly.
type (
	_ context.Context
)
